# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.request_field = QtWidgets.QTextEdit(self.centralwidget)
        self.request_field.setGeometry(QtCore.QRect(160, 70, 271, 71))
        self.request_field.setObjectName("request_field")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(140, 150, 381, 301))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 30, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Mistral")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setGeometry(QtCore.QRect(460, 80, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Mistral")
        font.setPointSize(11)
        self.button.setFont(font)
        self.button.setObjectName("button")
        self.error_label = QtWidgets.QLabel(self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(120, 440, 401, 121))
        font = QtGui.QFont()
        font.setFamily("Mistral")
        font.setPointSize(14)
        self.error_label.setFont(font)
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(530, 150, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Mistral")
        font.setPointSize(11)
        self.add_button.setFont(font)
        self.add_button.setObjectName("add_button")
        self.change_button = QtWidgets.QPushButton(self.centralwidget)
        self.change_button.setGeometry(QtCore.QRect(530, 200, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Mistral")
        font.setPointSize(11)
        self.change_button.setFont(font)
        self.change_button.setObjectName("change_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Запрос"))
        self.button.setText(_translate("MainWindow", "Найти"))
        self.add_button.setText(_translate("MainWindow", "Добавить"))
        self.change_button.setText(_translate("MainWindow", "Изменить"))
